name: Clojure Tests
on:
  push:
    paths:
      - '.github/**'
      - 'bin/test'
      - '**/*.clj'
      - '**/*.cljc'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17.0.0+35'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1435'
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-deps
      - name: Run tests
        run: bin/kaocha
